# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 006ac9f0a6cf3821e8c0a8c3959f9bece735f1383d76f3ff6603940459393178437395d9a0faf63c50a38b134729277a3a220addd7e6ccc765f34f838b9f24da

test:
  secret_key_base: 89122a24bb0fd506264d50017ec55a3ccf51d3de296be9d6976c892d7a876e429fa5d96da3bbce5b00e92633b0372bae9d5a1e840950b0c055b72407b676dd41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
